"""Batch ngspice adapter."""

from __future__ import annotations

import math
import os
import re
import subprocess
from pathlib import Path

from ..brief import SpiceDeck
from ..gates import GateCheck, check
from ..workspace import reject_symlinks, workspace_path

MEASURE_RE = re.compile(
    r"^\s*([A-Za-z][A-Za-z0-9_]*)\s*=\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][+-]?\d+)?)",
    re.MULTILINE | re.IGNORECASE,
)
INCLUDE_RE = re.compile(
    r"""^(\s*\.include\s+)(?:"([^"]+)"|'([^']+)'|(\S+))(.*)$""",
    re.IGNORECASE,
)
ANALYSIS_RE = re.compile(r"^\s*\.(?:ac|dc|noise|op|pz|tf|tran)\b", re.IGNORECASE)
MEASURE_RE_LINE = re.compile(r"^\s*\.meas(?:ure)?\b", re.IGNORECASE)


def render_deck(deck: SpiceDeck, workspace: Path) -> str:
    include_base = workspace
    if deck.netlist_path:
        netlist = workspace_path(deck.netlist_path, workspace)
        include_base = netlist.parent
        lines = netlist.read_text(encoding="utf-8").splitlines()
        lines = [
            line
            for line in lines
            if not MEASURE_RE_LINE.match(line) and not ANALYSIS_RE.match(line)
        ]
        existing = {line.strip().lower() for line in lines}
        additions: list[str] = []
        for statement in (*deck.models, *deck.analyses):
            normalized = statement.strip().lower()
            if normalized not in existing:
                additions.append(statement)
                existing.add(normalized)
        additions.extend(measure.statement for measure in deck.measures)
        end_indexes = [
            index
            for index, line in enumerate(lines)
            if re.match(r"^\s*\.end(?:\s|$)", line, re.IGNORECASE)
        ]
        if len(end_indexes) > 1:
            raise ValueError("SPICE netlist must contain at most one .end statement")
        end_index = end_indexes[0] if end_indexes else len(lines)
        has_end = bool(end_indexes)
        lines[end_index:end_index] = additions
        if not has_end:
            lines.append(".end")
        text = "\n".join(lines) + "\n"
    else:
        lines = ["* generated by simulation-agent"]
        for element in deck.elements or []:
            nodes = " ".join(element.nodes)
            model = f" {element.model}" if element.model else ""
            ref = (
                element.ref
                if element.ref.upper().startswith(element.kind)
                else element.kind + element.ref
            )
            lines.append(f"{ref} {nodes} {element.value}{model}")
        lines.extend(deck.models)
        lines.extend(deck.analyses)
        lines.extend(measure.statement for measure in deck.measures)
        lines.append(".end")
        text = "\n".join(lines) + "\n"
    return _resolve_includes(text, include_base, workspace)


def _resolve_includes(text: str, base: Path, workspace: Path) -> str:
    _reject_control_blocks(text, base, workspace, set())
    lines: list[str] = []
    for line in text.splitlines():
        match = INCLUDE_RE.match(line)
        if match is None:
            lines.append(line)
            continue
        include = next(value for value in match.groups()[1:4] if value is not None)
        path = Path(include)
        resolved = workspace_path(path if path.is_absolute() else base / path, workspace)
        if not resolved.is_file():
            raise FileNotFoundError(f"SPICE include does not exist: {include}")
        lines.append(f'{match.group(1)}"{resolved}"{match.group(5)}')
    return "\n".join(lines) + "\n"


def _reject_control_blocks(
    text: str,
    base: Path,
    workspace: Path,
    visited: set[Path],
) -> None:
    pending: list[tuple[str, Path]] = [(text, base)]
    while pending:
        source, source_base = pending.pop()
        for line in source.splitlines():
            if re.match(r"^\s*\.control(?:\s|$)", line, re.IGNORECASE):
                raise ValueError("SPICE .control blocks are not supported")
            match = INCLUDE_RE.match(line)
            if match is None:
                continue
            include = next(value for value in match.groups()[1:4] if value is not None)
            path = Path(include)
            resolved = workspace_path(
                path if path.is_absolute() else source_base / path,
                workspace,
            )
            if not resolved.is_file():
                raise FileNotFoundError(f"SPICE include does not exist: {include}")
            if resolved not in visited:
                visited.add(resolved)
                pending.append((resolved.read_text(encoding="utf-8"), resolved.parent))


def parse_measures(text: str, deck: SpiceDeck, returncode: int = 0) -> list[GateCheck]:
    values = {name.lower(): value for name, value in MEASURE_RE.findall(text)}
    results: list[GateCheck] = []
    for measure in deck.measures:
        gate_id = f"spice.{measure.name}"
        if returncode != 0:
            results.append(check(gate_id, "spice", "unknown", f"ngspice exited {returncode}"))
            continue
        if re.search(rf"\b{re.escape(measure.name)}\s*=\s*failed\b", text, re.IGNORECASE):
            results.append(check(gate_id, "spice", "unknown", "ngspice measurement failed"))
            continue
        value = values.get(measure.name.lower())
        if value is None:
            results.append(check(gate_id, "spice", "unknown", "measurement output is missing"))
            continue
        measured = float(value)
        if not math.isfinite(measured):
            results.append(check(gate_id, "spice", "unknown", "measurement is non-finite"))
            continue
        if measure.min is None and measure.max is None:
            results.append(
                check(
                    gate_id,
                    "spice",
                    "unknown",
                    "measurement has no acceptance bounds",
                    measured=measured,
                )
            )
            continue
        passed = (measure.min is None or measured >= measure.min) and (
            measure.max is None or measured <= measure.max
        )
        results.append(
            check(
                gate_id,
                "spice",
                "pass" if passed else "fail",
                f"measured {measured:.9g}",
                measured=measured,
                limit=f"min {measure.min}; max {measure.max}",
            )
        )
    if not results:
        results.append(check("spice.measurements", "spice", "unknown", "no measures declared"))
    return results


def run_ngspice(
    deck: SpiceDeck, workspace: Path, out_dir: Path
) -> tuple[list[GateCheck], dict[str, object]]:
    try:
        out_dir = workspace_path(out_dir, workspace)
        reject_symlinks(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        reject_symlinks(out_dir)
    except (OSError, ValueError) as exc:
        return [check("spice.output", "spice", "unknown", f"unsafe output directory: {exc}")], {}
    deck_path = out_dir / "deck.cir"
    log_path = out_dir / "run.log"
    try:
        deck_path.write_text(render_deck(deck, workspace), encoding="utf-8")
    except (OSError, ValueError) as exc:
        return [check("spice.deck", "spice", "unknown", str(exc))], {}
    binary = os.environ.get("SIM_NGSPICE", "ngspice")
    try:
        result = subprocess.run(
            [binary, "-b", "-o", str(log_path), deck_path.name],
            cwd=out_dir,
            capture_output=True,
            text=True,
            timeout=deck.timeout_s,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return [
            check(
                "spice.execution",
                "spice",
                "unknown",
                f"ngspice unavailable or timed out: {exc}",
                evidence=[str(deck_path)],
            )
        ], {}
    try:
        reject_symlinks(out_dir)
    except (OSError, ValueError) as exc:
        return [
            check(
                "spice.output",
                "spice",
                "unknown",
                f"unsafe generated output: {exc}",
                evidence=[str(deck_path)],
            )
        ], {}
    log = ""
    if log_path.is_file():
        log = log_path.read_text(encoding="utf-8", errors="replace")
    log += "\n" + result.stdout + "\n" + result.stderr
    return parse_measures(log, deck, result.returncode), {
        "deck": str(deck_path),
        "log": str(log_path),
        "returncode": result.returncode,
    }
